<?php

namespace App\Notifications;

use App\Models\PurchaseRequest;
use App\Enums\PurchaseRequestStatus;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;
use Illuminate\Support\Facades\URL;

class PurchaseRequestSentForApprovalNotification extends Notification implements ShouldQueue
{
    use Queueable;

    /**
     * @param PurchaseRequest $purchaseRequest
     * @param string|null $token optional token generated by service
     * @param \DateTimeInterface|null $expiresAt optional expiry for signed link (used only for text)
     */
    public function __construct(
        public PurchaseRequest $purchaseRequest,
        public ?string $token = null,
        public ?\DateTimeInterface $expiresAt = null
    ) {}

    public function via(object $notifiable): array
    {
        return ['mail', 'database'];
    }

    /**
     * Build temporary signed route to approve.
     */
    protected function buildApproveUrl(object $notifiable): string
    {
        $pr = $this->purchaseRequest;

        // prefer currentApprover id if provided by notifiable
        $approverId = $notifiable->id ?? $pr->current_approver_id;

        // create temporary signed route; expires in 7 days by default (or use $this->expiresAt)
        $expires = $this->expiresAt ?? now()->addDays(7);

        $url = URL::temporarySignedRoute(
            'pr.approve.link',
            $expires,
            [
                'id' => $pr->id,
                'approver_id' => $approverId,
            ]
        );

        // include token as query param if available (some implementations check token)
        if ($this->token) {
            $url .= (str_contains($url, '?') ? '&' : '?') . 'token=' . urlencode($this->token);
        }

        return $url;
    }

    public function toMail(object $notifiable): MailMessage
    {
        $pr = $this->purchaseRequest;
        $requesterName = $pr->requester?->name ?? '—';
        $department = $pr->department?->name ?? '—';
        $approveUrl = $this->buildApproveUrl($notifiable);

        $mail = (new MailMessage)
            ->subject("Approval required: {$pr->pr_number}")
            ->greeting("Hello {$notifiable->name},")
            ->line("A purchase request requires your approval.")
            ->line("**PR Number:** {$pr->pr_number}")
            ->line("**Requester:** {$requesterName}")
            ->line("**Department:** {$department}")
            ->line("**Purpose:** " . (\Str::limit($pr->purpose ?? '-', 200)))
            ->action('Open & Approve', $approveUrl);

        if ($this->expiresAt) {
            $mail->line('This approval link will expire on ' . $this->expiresAt->format('d M Y H:i') . '.');
        } else {
            $mail->line('This approval link will expire in 7 days.');
        }

        $mail->line('If you are not the intended approver, please ignore this email or contact your administrator.');

        return $mail;
    }

    public function toArray(object $notifiable): array
    {
        $pr = $this->purchaseRequest;

        return [
            'purchase_request_id' => $pr->id,
            'pr_number' => $pr->pr_number,
            'action' => 'sent_for_approval',
            'message' => "PR {$pr->pr_number} sent to you for approval",
            'approver_id' => $pr->current_approver_id,
        ];
    }
}
